### ISSUE TITLE
[+] Comando: /dicas

### ISSUE THREAD

**Issue by igorfradi** [lucasirleal/Bot-Discord-Comunistinha#4]
Mesmo esquema do bot Clóvis, mudando os textos para os que o Emerson planejou:

Macetes do Barman

Macete Entrada:
Aqui vai uns truque do nosso especialista para você aproveitar todas as batidas do campeão: 
Clica numa reação e bó ouvir os ensinamento! 

Macete Vermelha:
As mesas (canais) tem plaquinhas falando pra que servem nas suas mensagens fixadas!
Campeão, mostra pro compatriota como que faz! (GIF ensinando a ver mensagem fixada)

Macete Azul:
Os bêbado tão festejando a noite toda!
Dá uma bizoiada em como pôr os tampões de ouvido
(gif ensinando a silenciar o servidor)

Macete verde:
Tem uma mesa pra lá de barulhenta?
É só usar esse treco aqui: 
(gif ensinando a silenciar um chat)

Macete Amarelo:
Opa, não esquece de ver se a #carteira-perdida é sua! Se cadastra lá e tu vai ter acesso até as mesas VIP compadre!

Macete Roxo:
Tem uns cara trocando soco!
Se tu achar alguém desrespeitando as #normas-do-bar, é só chamar um dos @Championship 🍻]

**Comment by lucasirleal** [comment]
Adicionado em https://github.com/lucasirleal/Bot-Discord-Comunistinha/commit/4d63e3a5283819299c7bd32d79b31e06b95de13b
