### ISSUE TITLE
[+] Comando: /faq

### ISSUE THREAD

**Issue by igorfradi** [lucasirleal/Bot-Discord-Comunistinha#5]
Mesmo esquema que o bot Clóvis, mudando os textos para os que Emerson planejou:

Barmen Comunista

FAQ Principal
Tá com alguma pergunta? Desembucha!
É só reagir nos icones abaixo, e vamo dialogar parceiro.

FAQ JUIZ
    literalmente as regras

Comandos uteis
    Cada um dos nossos compatriotas serviçais gostam de ser tratado de um jeito e cada um tem sua batida especial. Dá uma olhada ai como chamar cada um:
Colocar comandos dos bots

FAQ sapinho
    “O clóvis é seu sapinho amigo. Ele foi criado pelo Estúdio Weasel, que pertence ao @hardokay e @IgorFradi.” - é com vocês seus créditos migos

**Comment by lucasirleal** [comment]
Adicionado em https://github.com/lucasirleal/Bot-Discord-Comunistinha/commit/0603e5576f2096a5bc0fb174bdfdfc52017531ed
