### ISSUE TITLE
[+] Possível sistema de níveis

### ISSUE THREAD

**Issue by igorfradi** [lucasirleal/Bot-Discord-Comunistinha#7]
Um diferencial seria um sistema de níveis, onde os usuários ganham uma quantidade aleatória de XP a cada intervalo x de tempo.

Os níveis garantem cargos diferenciados e benefícios personalizados no servidor.
Atualmente estamos utilizando o ProBot para essa feature, porém é pouco personalizável.

**Banindo canais de ganhar XP e enviando mensagens personalizadas no level up:**
![Screenshot_67](https://user-images.githubusercontent.com/35403819/90899662-a32a0780-e39e-11ea-8338-d85d626dc37c.png)

**Cargos personalizados para cada level up:**
![Screenshot_68](https://user-images.githubusercontent.com/35403819/90899718-b63cd780-e39e-11ea-89e3-d7a05cdaa045.png)

**Comandos informativos:**
![Screenshot_69](https://user-images.githubusercontent.com/35403819/90899774-cd7bc500-e39e-11ea-9614-0745d8407f55.png)

**Comment by lucasirleal** [comment]
Adicionado em https://github.com/lucasirleal/Bot-Discord-Comunistinha/commit/c47abcd62a9e279c7facd66548c2e5787dfa46dc
