### ISSUE TITLE
[~] Novos comandos com bugs nas permissões

### ISSUE THREAD

**Issue by igorfradi** [lucasirleal/Bot-Discord-Comunistinha#9]
As permissões dos novos comandos estão bugadas, pessoas sem admin não conseguem usa-los
![Screenshot_72](https://user-images.githubusercontent.com/35403819/91507556-89f7ee00-e8ab-11ea-9655-bb676e659494.png)

**Comment by lucasirleal** [comment]
Arrumado em https://github.com/lucasirleal/Bot-Discord-Comunistinha/commit/26a3609b7af7e6d6de046aa9375ba19c6d70eec7
